# Generated by Django 2.1.11 on 2020-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitresult',
            name='again',
            field=models.CharField(default='', max_length=200),
        ),
    ]
