# Generated by Django 2.1.11 on 2020-04-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='projectId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='testcaseId',
            field=models.CharField(max_length=200),
        ),
    ]
