# Generated by Django 2.1.11 on 2020-01-06 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('projectId', models.IntegerField()),
                ('content', models.TextField()),
                ('report_name', models.CharField(default='', max_length=255)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
    ]
