# Generated by Django 2.1.11 on 2020-05-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_splitresult_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitresult',
            name='again',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
