# Generated by Django 2.1.11 on 2020-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20200426_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.ImageField(upload_to='')),
                ('result_id_list', models.CharField(max_length=200)),
            ],
        ),
    ]
