# Generated by Django 2.1.11 on 2020-01-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_plan_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
