# Generated by Django 2.1.11 on 2020-01-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_delete_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.CharField(default='lixiaofeng', max_length=20),
        ),
    ]
