# Generated by Django 2.1.11 on 2020-04-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_taskrelation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskrelation',
            table='TaskRelation',
        ),
    ]
