# Generated by Django 2.1.11 on 2020-01-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20200113_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='error_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='result',
            name='step_num',
            field=models.IntegerField(default=0),
        ),
    ]
