# Generated by Django 2.1.11 on 2020-04-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20200426_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrelation',
            name='relation_id',
        ),
    ]
