# Generated by Django 2.1.11 on 2020-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20200120_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='error_name',
        ),
        migrations.RemoveField(
            model_name='result',
            name='step_num',
        ),
        migrations.AddField(
            model_name='splitresult',
            name='error_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='splitresult',
            name='step_num',
            field=models.IntegerField(default=0),
        ),
    ]
