# Generated by Django 2.1.11 on 2020-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_taskrelation_relation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrelation',
            name='result_id',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='taskrelation',
            name='result_id_list',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
